server:
    port: 8081
spring:
    application:
        name: EgarSchool
    datasource:
        password: egaroot
        url: jdbc:postgresql://localhost:5432/egardocuments
        username: postgres
    jpa:
        defer-datasource-initialization: true
        hibernate:
            ddl-auto: create
        show-sql: true
        properties:
            hibernate:
                format_sql: true
    sql:
        init:
            mode: always
